#!/usr/bin/env python3
import sys
import os
from pathlib import Path
# Root is 2 levels up from topics/<topic>/
root = str(Path(__file__).resolve().parent.parent.parent)
sys.path.append(root)
from cf_manager import ProblemManager

if __name__ == "__main__":
    manager = ProblemManager("diffArrays")
    manager.run()
